apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: velocity-proxy
        imagePullPolicy: Never
        ports:
        - containerPort: 25577
      serviceAccountName: proxy-sa
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 25577
      targetPort: 25577
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy-role
subjects:
- kind: ServiceAccount
  name: proxy-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-sa
automountServiceAccountToken: true
